# Generated by Django 3.2.5 on 2021-07-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memcard', '0002_word_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='author',
            new_name='by',
        ),
    ]
