# Generated by Django 3.2.5 on 2021-07-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memcard', '0003_rename_author_word_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='by',
            new_name='user',
        ),
    ]
